<?php $this->headTitle('Contact us' .' - ' .$this->config('core.siteName')); ?>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    var geocoder = new google.maps.Geocoder();

    function geocodePosition(pos) {
        geocoder.geocode({
            latLng: pos
        }, function (responses) {
            if (responses && responses.length > 0) {
                updateMarkerAddress(responses[0].formatted_address);
            } else {
                updateMarkerAddress('Cannot determine address at this location.');
            }
        });
    }

    function updateMarkerStatus(str) {
        document.getElementById('markerStatus').innerHTML = str;
    }

    function updateMarkerPosition(latLng) {
        document.getElementById('info').innerHTML = [
            latLng.lat(),
            latLng.lng()
        ].join(', ');
    }

    function updateMarkerAddress(str) {
        document.getElementById('address').innerHTML = str;
    }

    function initialize() {
        var latLng = new google.maps.LatLng(<?php echo $this->config('contact.coordinates')[0] ?>, <?php echo $this->config('contact.coordinates')[1] ?>);
        var map = new google.maps.Map(document.getElementById('mapCanvas'), {
            zoom: 8,
            center: latLng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        var marker = new google.maps.Marker({
            position: latLng,
            title: 'Point A',
            map: map,
            draggable: false,
            icon: '<?php echo $this->themePath(); ?>images/gmap_icon.png'
        });

        // Update current position info.
        updateMarkerPosition(latLng);
        geocodePosition(latLng);

        // Add dragging event listeners.
        google.maps.event.addListener(marker, 'dragstart', function () {
            updateMarkerAddress('Dragging...');
        });

        google.maps.event.addListener(marker, 'drag', function () {
            updateMarkerStatus('Dragging...');
            updateMarkerPosition(marker.getPosition());
        });

        google.maps.event.addListener(marker, 'dragend', function () {
            updateMarkerStatus('Drag ended');
            geocodePosition(marker.getPosition());
        });
    }

    // Onload handler to fire off the app.
    google.maps.event.addDomListener(window, 'load', initialize);
    
    //fade out
    $(document).ready(function(){
        if($('.message-f').length > 0) {
            $('.message-f').fadeOut(5000);
        }
    });
    
</script>
<style type="text/css">
    #mapCanvas {
        width: 100%;
        height: 400px;
    }

</style>
<div class="content-details">
    <div class="map">
        <div id="mapCanvas"></div>
    </div>
    <!-- end map -->
    
    <?php
        $message = $this->flashMessenger()->getMessages();
        if(isset($message) && count($message) > 0):
    ?>
        <div class="message-f">
            <i class="fa fa-check"></i>
        </div>
    <?php endif;?>
    
    <div class="col-md-4 information alpha">
        <?php echo $this->config('contact.companyInfo'); ?>
    </div>
    <div class="col-md-8 contact-form omega">
        <h2><?php echo $this->translate('Leave us a message'); ?></h2>
        <?php echo $this->form($form) ?>
    </div>
</div>