<?php echo $this->partial('layout/header-part') ?>
<div id="page">
    <?php echo $this->partial('common/header'); ?>
    <section id="content">
        <div class="container">
            <div class="row"><?php echo $content; ?></div>
        </div>
    </section>
    <!-- end content -->
    <?php echo $this->partial('common/footer'); ?>
</div>
<?php echo $this->partial('layout/footer-part') ?>